#pragma once

#include "Version.h"
#include "Utils.h"
#include "Logger.h"
#include "Token.h"
#include "Ast.h"
#include "Lexer.h"
#include "Parser.h"
#include "AstPass.h"
#include "ConstantFoldPass.h"
#include "TypeCheckPass.h"
#include "SyntaxCheckPass.h"
#include "Compiler.h"
#include "VM.h"